### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by ayushsarode** [ayushsarode/DSA-Learning-Kit#16]
Tell us how we can improve the docs and implement.

**Comment by csengineer1990** [comment]
Hi @ayushsarode I am participating for the first time in Hacktoberfest and I want to contribute to this issue. what have to do and how can I help here to improve the documentation?

**Comment by ayushsarode** [comment]
> Hi @ayushsarode I am participating for the first time in Hacktoberfest and I want to contribute to this issue. what have to do and how can I help here to improve the documentation?

We need your assistance in adding a table of contents and properly structuring it, as well as coming up with ideas for how to improve README.md.
